### PR TITLE
fixed parsing of Name - Jmeno - 1. serie

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by lubo** [comment]
I don't really see this taking any effect. Could you provide me with information about the current and required behavior, please ?

**Comment by jose1711** [comment]
try testing with http://serialy.sledujufilmy.cz/the-wire-spina-baltimoru/

**Comment by lubo** [comment]
Oh, I see. So, fix the commit message and I'll merge.

**Comment by jose1711** [comment]
sorry but i don't know how would you like me to fix it. hint?

**Comment by lubo** [comment]
Here you go, read [this](http://chris.beams.io/posts/git-commit/). You can edit the commit message using `git commit --amend` and force push the new commit using `git push -f`. Let me know if you find it too difficult.

**Comment by jose1711** [comment]
okay, so something like this would suffice?

> fixed parsing of series with multiple occurrences of " - " in name

**Comment by lubo** [comment]
Please, read the article.

**Comment by jose1711** [comment]
did my homework, thank you for pointing out the article. i believe body-less message in this form would be fine:

> Fix parsing of series with multiple occurences of " - " in name

**Comment by lubo** [comment]
Yup, that's way better. Force push it and I'll merge it.

**Pull request merged**
